Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here
+      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
@@ -16,7 +16,7 @@ commands:
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
@@ -31,51 +31,39 @@ commands:
             #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
-
+            
 jobs:
   build-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys:
-            - frontend-deps-{{ checksum "frontend/package-lock.json" }}
+          keys: [frontend-build]
       - run:
-          name: Install dependencies
+          name: Build front-end
           command: |
-            cd frontend
-            npm install
-      - run:
-          name: Build frontend
-          command: |
-            cd frontend
-            npm run build
+            # Your code here
+            exit 1
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps-{{ checksum "TIER/package-lock.json" }}
+          key: frontend-build
 
   build-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys:
-            - backend-deps-{{ checksum "backend/package-lock.json" }}
+          keys: [backend-build]
       - run:
-          name: Install dependencies
+          name: Back-end build
           command: |
-            cd backend
-            npm install
-      - run:
-          name: Build backend
-          command: |
-            cd backend
-            npm run build
+             # Your code here
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps-{{ checksum "TIER/package-lock.json" }}
+          key: backend-build
 
   test-frontend:
     docker:
@@ -84,7 +72,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-
+                
   test-backend:
     docker:
       # Docker image here
@@ -92,7 +80,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-
+            
   scan-frontend:
     docker:
       # Docker image here
@@ -111,7 +99,7 @@ jobs:
 
   deploy-infrastructure:
     docker:
-    # Docker image here that supports AWS CLI
+      # Docker image here that supports AWS CLI
     steps:
       # Checkout code from git
       - run:
@@ -141,7 +129,7 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     docker:
@@ -160,7 +148,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
@@ -177,7 +165,7 @@ jobs:
           command: |
             # Your code here
             exit 1
-    # Here's where you will add some code to rollback on failure
+     # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
@@ -198,8 +186,8 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
-
+      # Here's where you will add some code to rollback on failure      
+                    
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
@@ -215,11 +203,11 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
-      # Lightweight Docker image
+      # Lightweight Docker image 
     steps:
       # Checkout code from git
       - run:
@@ -238,7 +226,7 @@ jobs:
           name: Frontend smoke test.
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
@@ -253,26 +241,27 @@ jobs:
           name: Update cloudfront distribution
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure
+      # Here's where you will add some code to rollback on failure  
 
 cleanup:
-  docker:
-    # Docker image here
-  steps:
-    # Checkout code from git
-    - run:
-        name: Get old stack workflow id
-        command: |
-          # your code here
-          export OldWorkflowID="the id here"
-          export STACKS=[] #put the list of stacks here
-    - run:
-        name: Remove old stacks and files
-        command: |
-          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-          then
+    docker:
+      # Docker image here
+    steps:
+      # Checkout code from git
+      - run:
+          name: Get old stack workflow id
+          command: |
             # your code here
-          fi
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
+            
 
 workflows:
   default:
