Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -394,6 +394,7 @@ jobs:
               --output text)
 
             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+ 
             if curl -s $API_URL/api/status | grep "ok"
             then
               exit 0
@@ -403,13 +404,16 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-              then
-                  exit 0
-              else
-                  exit 1
-              fi
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              # This is the intentional error, if "Welcome" is indeed in the response this step will exit with exit code 1
+              exit 0
+            else
+              exit 2
+            fi
+      - destroy-environment
+      - revert-migrations 
     
   
               
